Document: musikernel1
Title: Debian musikernel1 Manual
Author: <insert document author here>
Abstract: This manual describes what musikernel1 is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/musikernel1/musikernel1.sgml.gz

Format: postscript
Files: /usr/share/doc/musikernel1/musikernel1.ps.gz

Format: text
Files: /usr/share/doc/musikernel1/musikernel1.text.gz

Format: HTML
Index: /usr/share/doc/musikernel1/html/index.html
Files: /usr/share/doc/musikernel1/html/*.html
